name: Lint Code and Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Download Spacy model
      run: python -m spacy download en_core_web_md-2.2.0 --direct
    - name: Lint code
      run: make
      env:
        PYTHONPATH: tests/
    - name: Run tests
      run: python -m pytest -n auto --durations=0 tests/
      env:
        PYTHONPATH: tests/

